version: "3.9"
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage

  crawler:
    build: ./services/crawler_service
    volumes:
      - ./inputs:/app/inputs
      - ./data:/app/data
    env_file: .env

  vector:
    build: ./services/vector_service
    depends_on:
      - qdrant
    volumes:
      - ./data:/app/data
    env_file: .env

  api:
    build: ./services/api_service
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    volumes:
      - ./data:/app/data
    env_file: .env
